[package]
name = "actix-web-codegen"
version = "0.5.0-beta.6"
description = "Routing and runtime macros for Actix Web"
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
authors = [
    "Nikolay Kim <fafhrd91@gmail.com>",
    "Rob Ede <robjtede@icloud.com>",
]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1", features = ["full", "parsing"] }
proc-macro2 = "1"
actix-router = "0.5.0-beta.2"

[dev-dependencies]
actix-macros = "0.2.3"
actix-rt = "2.2"
# actix-test = "0.1.0-beta.8"
actix-test = { git = "https://github.com/pashinin/actix-web.git", branch = "version-fix", package = "actix-test" }
actix-utils = "3.0.0"
# actix-web = "4.0.0-beta.14"
actix-web = { git = "https://github.com/pashinin/actix-web.git", branch = "version-fix", package = "actix-web" }

futures-core = { version = "0.3.7", default-features = false, features = ["alloc"] }
trybuild = "1"
rustversion = "1"
